BUG: don't rely on plugin discovery order
Installing the extension led to the following error messages.

So this change only gets the references to other plugins when needed, which
happens after the full application has started up.


[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - Session start time .......: 2018-08-21 10:07:11
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - Slicer version ...........: 4.9.0-2018-08-17 (revision 27353) macosx-amd64 - installed release
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - Operating system .........: Mac OS X / 10.13.6 / 17G65 - 64-bit
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - Memory ...................: 65536 MB physical, 5120 MB virtual
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - CPU ......................: GenuineIntel Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz, 12 cores, 24 logical processors
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, Sequential threading
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - Developer mode enabled ...: yes
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - Prefer executable CLI ....: yes
[DEBUG][Qt] 21.08.2018 10:07:11 [] (unknown:0) - Additional module paths ..: /Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/PedicleScrewSimulator/lib/Slicer-4.9/qt-scripted-modules, /Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/MarkupsToModel/lib/Slicer-4.9/qt-loadable-modules, /Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/SegmentEditorExtraEffects/lib/Slicer-4.9/qt-scripted-modules, /Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/SlicerDMRI/lib/Slicer-4.9/cli-modules, /Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/SlicerDMRI/lib/Slicer-4.9/qt-loadable-modules, /Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/SlicerDMRI/lib/Slicer-4.9/qt-scripted-modules, /Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/UKFTractography/lib/Slicer-4.9/cli-modules, /Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/UKFTractography/lib/Slicer-4.9/qt-loadable-modules, /Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/UKFTractography/lib/Slicer-4.9/qt-scripted-modules, /Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/DCMQI/lib/Slicer-4.9/cli-modules, /Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/QuantitativeReporting/lib/Slicer-4.9/qt-scripted-modules, /Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/SlicerDevelopmentToolbox/lib/Slicer-4.9/qt-scripted-modules
[DEBUG][Python] 21.08.2018 10:07:13 [Python] (/Applications/Slicer-4.9.0-2018-08-17.app/Contents/lib/Python/lib/python2.7/site-packages/git/cmd.py:719) - Popen(['git', 'version'], cwd=/Applications, universal_newlines=False, shell=None)
[DEBUG][Python] 21.08.2018 10:07:13 [Python] (/Applications/Slicer-4.9.0-2018-08-17.app/Contents/lib/Python/lib/python2.7/site-packages/git/cmd.py:719) - Popen(['git', 'version'], cwd=/Applications, universal_newlines=False, shell=None)
[DEBUG][Python] 21.08.2018 10:07:17 [Python] (/Applications/Slicer-4.9.0-2018-08-17.app/Contents/lib/Slicer-4.9/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: Annotations
[CRITICAL][FD] 21.08.2018 10:07:17 [] (unknown:0) - [13883:59139:0821/100717.495040:ERROR:gl_context_cgl.cc(137)] Error creating context.
[DEBUG][Python] 21.08.2018 10:07:21 [Python] (/Applications/Slicer-4.9.0-2018-08-17.app/Contents/lib/Slicer-4.9/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 21.08.2018 10:07:21 [Python] (/Applications/Slicer-4.9.0-2018-08-17.app/Contents/lib/Slicer-4.9/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py:36) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Qt] 21.08.2018 10:07:23 [] (unknown:0) - Switch to module:  "Welcome"
[CRITICAL][Stream] 21.08.2018 10:07:24 [] (unknown:0) - Traceback (most recent call last):
[INFO][FD] 21.08.2018 10:07:24 [] (unknown:0) - AVDCreateGPUAccelerator: Error loading GPU renderer
[CRITICAL][Stream] 21.08.2018 10:07:24 [] (unknown:0) -   File "/Applications/Slicer-4.9.0-2018-08-17.app/Contents/bin/../lib/Slicer-4.9/qt-scripted-modules/DICOM.py", line 76, in performPostModuleDiscoveryTasks
[CRITICAL][Stream] 21.08.2018 10:07:24 [] (unknown:0) -     DICOMLib.setDatabasePrecacheTags()
[CRITICAL][Stream] 21.08.2018 10:07:24 [] (unknown:0) -   File "/Applications/Slicer-4.9.0-2018-08-17.app/Contents/lib/Slicer-4.9/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 40, in setDatabasePrecacheTags
[CRITICAL][Stream] 21.08.2018 10:07:24 [] (unknown:0) -     plugin = slicer.modules.dicomPlugins[pluginClass]()
[CRITICAL][Stream] 21.08.2018 10:07:24 [] (unknown:0) -   File "/Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/QuantitativeReporting/lib/Slicer-4.9/qt-scripted-modules/DICOMTID1500Plugin.py", line 26, in __init__
[CRITICAL][Stream] 21.08.2018 10:07:24 [] (unknown:0) -     self.rwvmPlugin = slicer.modules.dicomPlugins["DICOMRWVMPlugin"]()
[CRITICAL][Stream] 21.08.2018 10:07:24 [] (unknown:0) - KeyError: 'DICOMRWVMPlugin'
[DEBUG][Qt] 21.08.2018 10:07:40 [] (unknown:0) - Switch to module:  "DICOM"
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -   File "/Applications/Slicer-4.9.0-2018-08-17.app/Contents/bin/../lib/Slicer-4.9/qt-scripted-modules/DICOM.py", line 332, in setup
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -     self.detailsPopup = self.getSavedDICOMDetailsWidgetType()()
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -   File "/Applications/Slicer-4.9.0-2018-08-17.app/Contents/lib/Slicer-4.9/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 1011, in __init__
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -     super(DICOMDetailsWindow, self).__init__(dicomBrowser, parent)
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -   File "/Applications/Slicer-4.9.0-2018-08-17.app/Contents/lib/Slicer-4.9/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 980, in __init__
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -     DICOMDetailsBase.__init__(self, dicomBrowser)
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -   File "/Applications/Slicer-4.9.0-2018-08-17.app/Contents/lib/Slicer-4.9/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 107, in __init__
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -     setDatabasePrecacheTags(self.dicomBrowser)
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -   File "/Applications/Slicer-4.9.0-2018-08-17.app/Contents/lib/Slicer-4.9/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 40, in setDatabasePrecacheTags
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -     plugin = slicer.modules.dicomPlugins[pluginClass]()
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -   File "/Applications/Slicer-4.9.0-2018-08-17.app/Contents/Extensions-27353/QuantitativeReporting/lib/Slicer-4.9/qt-scripted-modules/DICOMTID1500Plugin.py", line 26, in __init__
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -     self.rwvmPlugin = slicer.modules.dicomPlugins["DICOMRWVMPlugin"]()
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) - KeyError: 'DICOMRWVMPlugin'
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -   File "/Applications/Slicer-4.9.0-2018-08-17.app/Contents/bin/../lib/Slicer-4.9/qt-scripted-modules/DICOM.py", line 273, in enter
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -     self.onOpenDetailsPopup()
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -   File "/Applications/Slicer-4.9.0-2018-08-17.app/Contents/bin/../lib/Slicer-4.9/qt-scripted-modules/DICOM.py", line 373, in onOpenDetailsPopup
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) -     if not isinstance(self.detailsPopup, self.getSavedDICOMDetailsWidgetType()):
[CRITICAL][Stream] 21.08.2018 10:07:41 [] (unknown:0) - AttributeError: DICOMWidget instance has no attribute 'detailsPopup'